name: Build Besmi Android APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'  
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Create Besmi mobile project
      run: |
        mkdir besmi-mobile
        cd besmi-mobile
        
        # Create package.json
        cat > package.json << 'EOF'
        {
          "name": "besmi-mobile",
          "version": "1.0.0",
          "dependencies": {
            "@capacitor/android": "^5.7.0",
            "@capacitor/cli": "^5.7.0",
            "@capacitor/core": "^5.7.0"
          }
        }
        EOF
        
        # Create web directory and content
        mkdir -p www
        
        # Create app icon (Besmi logo)
        mkdir -p android/app/src/main/res/mipmap-hdpi
        mkdir -p android/app/src/main/res/mipmap-mdpi
        mkdir -p android/app/src/main/res/mipmap-xhdpi
        mkdir -p android/app/src/main/res/mipmap-xxhdpi
        mkdir -p android/app/src/main/res/mipmap-xxxhdpi
        
        # Install ImageMagick for icon conversion
        sudo apt-get update && sudo apt-get install -y imagemagick
        
        # Generate SVG icon and convert to different sizes
        cat > icon.svg << 'EOF'
        <svg width="512" height="512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
          <defs>
            <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="100%">
              <stop offset="0%" style="stop-color:#FF8DC7;stop-opacity:1" />
              <stop offset="100%" style="stop-color:#89CFF0;stop-opacity:1" />
            </linearGradient>
          </defs>
          <rect width="512" height="512" rx="120" ry="120" fill="url(#grad)"/>
          <text x="256" y="350" font-family="Arial, sans-serif" font-size="300" font-weight="700" text-anchor="middle" fill="white" letter-spacing="-10">B</text>
        </svg>
        EOF
        cat > www/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
          <title>Besmi</title>
          <style>
            * { 
              margin: 0; padding: 0; box-sizing: border-box;
              -webkit-tap-highlight-color: transparent;
            }
            html, body {
              height: 100%; overflow: hidden;
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            }
            body {
              background: linear-gradient(135deg, #FF8DC7 0%, #89CFF0 100%);
              display: flex; align-items: center; justify-content: center;
            }
            .splash-container {
              text-align: center; background: white; padding: 60px 40px;
              border-radius: 24px; box-shadow: 0 20px 60px rgba(0,0,0,0.15);
              max-width: 350px; width: 85%; animation: fadeIn 0.8s ease-out;
            }
            .logo {
              width: 100px; height: 100px; margin: 0 auto 30px;
              background: linear-gradient(135deg, #FF8DC7 0%, #89CFF0 100%);
              border-radius: 24px; display: flex; align-items: center; justify-content: center;
              font-size: 40px; font-weight: 700; color: white; letter-spacing: -1px;
              box-shadow: 0 8px 25px rgba(255, 141, 199, 0.3);
            }
            h1 { 
              font-size: 32px; font-weight: 700; color: #1a1a1a; 
              margin-bottom: 8px; letter-spacing: -0.5px;
            }
            .tagline { 
              font-size: 16px; color: #666; margin-bottom: 40px; 
              line-height: 1.4; font-weight: 400;
            }
            .loading-container {
              display: flex; align-items: center; justify-content: center;
              color: #888; font-size: 16px; font-weight: 500;
            }
            .spinner {
              width: 24px; height: 24px; margin-right: 12px;
              border: 3px solid #f0f0f0; border-top: 3px solid #FF8DC7;
              border-radius: 50%; animation: spin 1s linear infinite;
            }
            .status-text {
              animation: pulse 2s ease-in-out infinite;
            }
            @keyframes spin { 
              0% { transform: rotate(0deg); } 
              100% { transform: rotate(360deg); } 
            }
            @keyframes fadeIn {
              0% { opacity: 0; transform: translateY(20px); }
              100% { opacity: 1; transform: translateY(0); }
            }
            @keyframes pulse {
              0%, 100% { opacity: 0.7; }
              50% { opacity: 1; }
            }
          </style>
        </head>
        <body>
          <div class="splash-container">
            <div class="logo">B</div>
            <h1>Besmi</h1>
            <p class="tagline">Professional Lash Booking Platform</p>
            <div class="loading-container">
              <div class="spinner"></div>
              <span class="status-text">Opening platform...</span>
            </div>
          </div>
          
          <script>
            // Ensure DOM is loaded
            document.addEventListener('DOMContentLoaded', function() {
              console.log('Besmi app loaded successfully');
              
              // Redirect after splash screen
              setTimeout(function() {
                console.log('Redirecting to platform...');
                window.location.href = "https://besmi.replit.app";
              }, 2500);
            });
            
            // Fallback redirect
            setTimeout(function() {
              if (window.location.href.indexOf('besmi.replit.app') === -1) {
                window.location.href = "https://besmi.replit.app";
              }
            }, 3000);
          </script>
        </body>
        </html>
        EOF
        
        # Create capacitor config
        cat > capacitor.config.json << 'EOF'
        {
          "appId": "com.besmi.lashbooking",
          "appName": "Besmi",
          "webDir": "www",
          "server": {
            "url": "https://besmi.replit.app",
            "cleartext": true,
            "allowNavigation": ["https://besmi.replit.app"]
          },
          "android": {
            "allowMixedContent": true,
            "captureInput": true,
            "webContentsDebuggingEnabled": true
          },
          "plugins": {
            "SplashScreen": {
              "launchShowDuration": 2000,
              "backgroundColor": "#FF8DC7",
              "showSpinner": false,
              "androidSpinnerStyle": "small",
              "spinnerColor": "#FFFFFF"
            },
            "StatusBar": {
              "style": "light",
              "backgroundColor": "#FF8DC7"
            }
          }
        }
        EOF
      
    - name: Install dependencies and build
      run: |
        cd besmi-mobile
        npm install
        npx cap add android
        
        # Convert SVG to PNG icons for Android
        convert icon.svg -resize 72x72 android/app/src/main/res/mipmap-hdpi/ic_launcher.png
        convert icon.svg -resize 48x48 android/app/src/main/res/mipmap-mdpi/ic_launcher.png
        convert icon.svg -resize 96x96 android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
        convert icon.svg -resize 144x144 android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
        convert icon.svg -resize 192x192 android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
        
        # Also create round icons
        convert icon.svg -resize 72x72 android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
        convert icon.svg -resize 48x48 android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
        convert icon.svg -resize 96x96 android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
        convert icon.svg -resize 144x144 android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
        convert icon.svg -resize 192x192 android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
        
        npx cap copy android
        npx cap sync android
      
    - name: Build Android APK
      run: |
        cd besmi-mobile
        chmod +x android/gradlew
        cd android
        ./gradlew assembleDebug --no-daemon --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: besmi-android-app
        path: besmi-mobile/android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Build Summary
      run: |
        echo "âœ… Besmi Android APK built successfully!"
        echo "ðŸ“± App: com.besmi.lashbooking"  
        echo "ðŸŒ Platform: https://besmi.replit.app"
        echo "ðŸ“¦ Download APK from artifacts section"
