name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Create project with Capacitor v4
      run: |
        echo '{
          "name": "besmi-mobile",
          "version": "1.0.0",
          "dependencies": {
            "@capacitor/core": "^4.8.0",
            "@capacitor/cli": "^4.8.0",
            "@capacitor/android": "^4.8.0"
          }
        }' > package.json
        
        mkdir -p dist
        cat > dist/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Besmi - Lash Booking Platform</title>
          <style>
            body {
              margin: 0; padding: 0;
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
              background: linear-gradient(135deg, #FF8DC7 0%, #89CFF0 100%);
              min-height: 100vh; display: flex; align-items: center; justify-content: center;
            }
            .container {
              text-align: center; padding: 40px 20px; background: white;
              border-radius: 20px; box-shadow: 0 20px 40px rgba(0,0,0,0.1);
              max-width: 400px; margin: 20px;
            }
            .logo {
              width: 80px; height: 80px;
              background: linear-gradient(135deg, #FF8DC7 0%, #89CFF0 100%);
              border-radius: 20px; margin: 0 auto 20px;
              display: flex; align-items: center; justify-content: center;
              font-size: 32px; font-weight: bold; color: white;
            }
            h1 { color: #333; margin: 20px 0 10px; font-size: 28px; }
            p { color: #666; margin: 10px 0 30px; font-size: 16px; line-height: 1.5; }
            .loading {
              display: inline-block; width: 20px; height: 20px;
              border: 3px solid #f3f3f3; border-top: 3px solid #FF8DC7;
              border-radius: 50%; animation: spin 1s linear infinite; margin-right: 10px;
            }
            @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
            .status { color: #888; font-size: 14px; margin-top: 20px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="logo">B</div>
            <h1>Besmi</h1>
            <p>Professional Lash Booking Platform</p>
            <div class="status">
              <div class="loading"></div>
              Connecting to platform...
            </div>
          </div>
          <script>
            setTimeout(() => { window.location.href = "https://besmi.replit.app"; }, 2000);
          </script>
        </body>
        </html>
        EOF
        
        cat > capacitor.config.json << 'EOF'
        {
          "appId": "com.besmi.lashbooking",
          "appName": "Besmi",
          "webDir": "dist",
          "server": {
            "url": "https://besmi.replit.app",
            "cleartext": true
          },
          "android": {
            "allowMixedContent": true
          }
        }
        EOF
      
    - name: Install dependencies
      run: |
        npm install
        npm install -g @capacitor/cli@4.8.0
      
    - name: Initialize and build Capacitor project
      run: |
        npx cap add android
        npx cap sync android
      
    - name: Build Android APK
      run: |
        chmod +x android/gradlew
        cd android
        ./gradlew assembleDebug --no-daemon --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: besmi-android-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
