name: Besmi Branded Mobile App Build

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'  
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y imagemagick
      
    - name: Create Besmi mobile app
      run: |
        mkdir besmi-mobile-app
        cd besmi-mobile-app
        
        # Create package.json
        cat > package.json << 'EOF'
        {
          "name": "besmi-mobile-app",
          "version": "1.0.0",
          "dependencies": {
            "@capacitor/core": "^6.1.0",
            "@capacitor/cli": "^6.1.0",
            "@capacitor/android": "^6.1.0"
          }
        }
        EOF
        
        # Install dependencies
        npm install
        
        # Capacitor configuration
        cat > capacitor.config.json << 'EOF'
        {
          "appId": "com.besmi.app",
          "appName": "Besmi",
          "webDir": "www",
          "server": {
            "url": "https://besmi.com/auth",
            "cleartext": true
          }
        }
        EOF
        
        # Create web directory with beautiful branded UI
        mkdir -p www
        
        cat > www/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Besmi - Professional Lash Booking</title>
            <style>
                * { margin: 0; padding: 0; box-sizing: border-box; }
                
                body {
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    display: flex; align-items: center; justify-content: center;
                    min-height: 100vh; padding: 20px;
                    overflow: hidden;
                }
                
                .container {
                    text-align: center; max-width: 400px; width: 100%;
                    background: rgba(255, 255, 255, 0.95);
                    border-radius: 24px; padding: 40px 30px;
                    backdrop-filter: blur(20px);
                    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
                    animation: slideUp 0.8s ease-out;
                }
                
                @keyframes slideUp {
                    from { opacity: 0; transform: translateY(50px); }
                    to { opacity: 1; transform: translateY(0); }
                }
                
                .logo-container {
                    width: 120px; height: 120px; background: #000;
                    border-radius: 24px; display: flex; align-items: center; 
                    justify-content: center; margin: 0 auto 30px;
                    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4);
                    position: relative; overflow: hidden;
                }
                
                .logo-container::before {
                    content: ''; position: absolute; top: -2px; left: -2px;
                    right: -2px; bottom: -2px; background: linear-gradient(45deg, #ff6b6b, #4ecdc4, #45b7d1, #96ceb4);
                    border-radius: 26px; z-index: -1;
                    animation: rotate 3s linear infinite;
                }
                
                @keyframes rotate {
                    0% { transform: rotate(0deg); }
                    100% { transform: rotate(360deg); }
                }
                
                .logo-text {
                    font-size: 56px; font-weight: 300; color: white;
                    font-family: 'Georgia', serif; letter-spacing: -2px;
                    text-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
                }
                
                h1 {
                    font-size: 32px; font-weight: 700; color: #333;
                    margin-bottom: 8px; letter-spacing: -0.5px;
                }
                
                .tagline {
                    font-size: 16px; color: #666; margin-bottom: 40px;
                    font-weight: 400; line-height: 1.4;
                }
                
                .features {
                    display: flex; justify-content: space-around;
                    margin-bottom: 40px; flex-wrap: wrap; gap: 20px;
                }
                
                .feature {
                    text-align: center; flex: 1; min-width: 100px;
                }
                
                .feature-icon {
                    width: 50px; height: 50px; background: linear-gradient(135deg, #667eea, #764ba2);
                    border-radius: 12px; display: flex; align-items: center;
                    justify-content: center; margin: 0 auto 8px;
                    color: white; font-size: 20px;
                }
                
                .feature-text {
                    font-size: 12px; color: #666; font-weight: 500;
                }
                
                .loading-section {
                    margin-bottom: 30px;
                }
                
                .loader {
                    width: 50px; height: 50px; border: 3px solid #f0f0f0;
                    border-top: 3px solid #667eea; border-radius: 50%;
                    animation: spin 1s ease-in-out infinite;
                    margin: 0 auto 20px;
                }
                
                @keyframes spin {
                    0% { transform: rotate(0deg); }
                    100% { transform: rotate(360deg); }
                }
                
                .status {
                    font-size: 16px; color: #667eea; font-weight: 600;
                    margin-bottom: 10px;
                }
                
                .progress-bar {
                    width: 100%; height: 4px; background: #f0f0f0;
                    border-radius: 2px; overflow: hidden; margin-bottom: 20px;
                }
                
                .progress-fill {
                    height: 100%; background: linear-gradient(90deg, #667eea, #764ba2);
                    width: 0%; animation: progress 3s ease-in-out;
                }
                
                @keyframes progress {
                    0% { width: 0%; }
                    50% { width: 70%; }
                    100% { width: 100%; }
                }
                
                .welcome-text {
                    font-size: 14px; color: #888; line-height: 1.5;
                }
                
                .floating-shapes {
                    position: absolute; width: 100%; height: 100%;
                    overflow: hidden; z-index: -1;
                }
                
                .shape {
                    position: absolute; opacity: 0.1;
                    animation: float 6s ease-in-out infinite;
                }
                
                .shape:nth-child(1) {
                    top: 10%; left: 10%; width: 60px; height: 60px;
                    background: #ff6b6b; border-radius: 50%;
                    animation-delay: 0s;
                }
                
                .shape:nth-child(2) {
                    top: 20%; right: 10%; width: 40px; height: 40px;
                    background: #4ecdc4; border-radius: 20%;
                    animation-delay: 2s;
                }
                
                .shape:nth-child(3) {
                    bottom: 20%; left: 20%; width: 50px; height: 50px;
                    background: #45b7d1; border-radius: 50%;
                    animation-delay: 4s;
                }
                
                @keyframes float {
                    0%, 100% { transform: translateY(0px) rotate(0deg); }
                    50% { transform: translateY(-20px) rotate(180deg); }
                }
            </style>
        </head>
        <body>
            <div class="floating-shapes">
                <div class="shape"></div>
                <div class="shape"></div>
                <div class="shape"></div>
            </div>
            
            <div class="container">
                <div class="logo-container">
                    <div class="logo-text">B</div>
                </div>
                
                <h1>Besmi</h1>
                <p class="tagline">Professional Lash Booking Platform</p>
                
                <div class="features">
                    <div class="feature">
                        <div class="feature-icon">📅</div>
                        <div class="feature-text">Smart Booking</div>
                    </div>
                    <div class="feature">
                        <div class="feature-icon">💳</div>
                        <div class="feature-text">Easy Payments</div>
                    </div>
                    <div class="feature">
                        <div class="feature-icon">👥</div>
                        <div class="feature-text">Client Management</div>
                    </div>
                </div>
                
                <div class="loading-section">
                    <div class="loader"></div>
                    <div class="status">Connecting to your account...</div>
                    <div class="progress-bar">
                        <div class="progress-fill"></div>
                    </div>
                </div>
                
                <p class="welcome-text">
                    Welcome to the future of lash business management. 
                    Get ready to streamline your bookings and grow your business.
                </p>
            </div>
            
            <script>
                let progress = 0;
                const messages = [
                    "Initializing secure connection...",
                    "Loading your workspace...",
                    "Preparing your dashboard...",
                    "Almost ready..."
                ];
                
                const statusEl = document.querySelector('.status');
                
                function updateStatus() {
                    if (progress < messages.length) {
                        statusEl.textContent = messages[progress];
                        progress++;
                        setTimeout(updateStatus, 800);
                    } else {
                        statusEl.textContent = "Redirecting to login...";
                        setTimeout(() => {
                            window.location.href = 'https://besmi.com/auth';
                        }, 1000);
                    }
                }
                
                setTimeout(updateStatus, 1000);
            </script>
        </body>
        </html>
        EOF
        
        # Initialize Capacitor project
        npx cap init "Besmi" "com.besmi.app" --web-dir=www
        
        # Add Android platform
        npx cap add android
        
        # Create app icon directories
        mkdir -p android/app/src/main/res/mipmap-mdpi
        mkdir -p android/app/src/main/res/mipmap-hdpi
        mkdir -p android/app/src/main/res/mipmap-xhdpi
        mkdir -p android/app/src/main/res/mipmap-xxhdpi
        mkdir -p android/app/src/main/res/mipmap-xxxhdpi
        
        # Generate high-quality Besmi "B" logo icons with proper serif font
        convert -size 48x48 -background black -fill white -font Times-Bold -pointsize 36 -gravity center label:"B" android/app/src/main/res/mipmap-mdpi/ic_launcher.png
        convert -size 72x72 -background black -fill white -font Times-Bold -pointsize 54 -gravity center label:"B" android/app/src/main/res/mipmap-hdpi/ic_launcher.png
        convert -size 96x96 -background black -fill white -font Times-Bold -pointsize 72 -gravity center label:"B" android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
        convert -size 144x144 -background black -fill white -font Times-Bold -pointsize 108 -gravity center label:"B" android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
        convert -size 192x192 -background black -fill white -font Times-Bold -pointsize 144 -gravity center label:"B" android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
        
        # Add rounded corners to match modern Android icons
        for size in 48 72 96 144 192; do
            case $size in
                48) dir="mdpi" ;;
                72) dir="hdpi" ;;
                96) dir="xhdpi" ;;
                144) dir="xxhdpi" ;;
                192) dir="xxxhdpi" ;;
            esac
            
            # Create rounded version for modern Android
            convert android/app/src/main/res/mipmap-$dir/ic_launcher.png \
                \( -size ${size}x${size} xc:none -draw "roundrectangle 0,0 $((size-1)),$((size-1)) $((size/8)),$((size/8))" \) \
                -compose SrcIn -composite \
                android/app/src/main/res/mipmap-$dir/ic_launcher_round.png
        done
        
        # Sync Capacitor with Android
        npx cap sync android
        
        # Build Android APK
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug
        
    - name: Upload Besmi APK
      uses: actions/upload-artifact@v4
      with:
        name: besmi-branded-mobile-app
        path: besmi-mobile-app/android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Build complete
      run: |
        echo "✅ Besmi branded mobile app built successfully"
        echo "✅ Features elegant Besmi 'B' logo with black background"
        echo "✅ Beautiful animated UI with brand colors and features showcase"
        echo "✅ Progressive loading experience before auth redirect"
        echo "✅ Opens https://besmi.com/auth after branded introduction"
        echo "✅ Download APK from Actions artifacts"
