name: Build Besmi Android APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'  
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y imagemagick
      
    - name: Create Besmi mobile app
      run: |
        mkdir besmi-mobile && cd besmi-mobile
        
        # Package.json
        cat > package.json << 'EOF'
        {
          "name": "besmi-mobile",
          "version": "1.0.0",
          "dependencies": {
            "@capacitor/android": "^5.7.0",
            "@capacitor/cli": "^5.7.0",
            "@capacitor/core": "^5.7.0"
          }
        }
        EOF
        
        npm install
        
        # Capacitor config
        cat > capacitor.config.json << 'EOF'
        {
          "appId": "com.besmi.lashbooking",
          "appName": "Besmi",
          "webDir": "www",
          "server": {
            "url": "https://besmi.replit.app",
            "cleartext": true,
            "allowNavigation": ["https://besmi.replit.app"]
          },
          "android": {
            "allowMixedContent": true,
            "captureInput": true,
            "webContentsDebuggingEnabled": true
          }
        }
        EOF
        
        # Web content
        mkdir -p www
        cat > www/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Besmi</title>
          <style>
            body {
              margin: 0; padding: 0; height: 100vh;
              background: white; display: flex;
              align-items: center; justify-content: center;
              font-family: system-ui, -apple-system, sans-serif;
            }
            .container {
              text-align: center; padding: 40px;
            }
            .logo {
              width: 100px; height: 100px; margin: 0 auto 20px;
              background: white; border: 2px solid #eee;
              border-radius: 20px; display: flex;
              align-items: center; justify-content: center;
              font-size: 50px; font-weight: bold; color: black;
            }
            h1 { margin: 20px 0 10px; font-size: 28px; color: #333; }
            p { margin: 0 0 30px; color: #666; }
            .spinner {
              width: 20px; height: 20px; margin: 0 auto;
              border: 2px solid #eee; border-top: 2px solid #333;
              border-radius: 50%; animation: spin 1s linear infinite;
            }
            @keyframes spin { to { transform: rotate(360deg); } }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="logo">B</div>
            <h1>Besmi</h1>
            <p>Professional Lash Booking Platform</p>
            <div class="spinner"></div>
          </div>
          <script>
            setTimeout(() => {
              window.location.href = "https://besmi.replit.app";
            }, 2000);
          </script>
        </body>
        </html>
        EOF
        
        # Add Android platform
        npx cap add android
        
        # Create Android app icon resources
        mkdir -p android/app/src/main/res/drawable
        
        # Create vector drawable for app icon
        cat > android/app/src/main/res/drawable/ic_launcher_foreground.xml << 'EOF'
        <vector xmlns:android="http://schemas.android.com/apk/res/android"
            android:width="108dp"
            android:height="108dp"
            android:viewportWidth="108"
            android:viewportHeight="108">
          <group android:scaleX="0.8"
              android:scaleY="0.8"
              android:pivotX="54"
              android:pivotY="54">
            <path
                android:pathData="M54,54m-30,0a30,30 0,1 1,60 0a30,30 0,1 1,-60 0"
                android:fillColor="#FFFFFF"
                android:strokeColor="#F0F0F0"
                android:strokeWidth="2"/>
            <text
                android:text="B"
                android:textSize="28sp"
                android:textColor="#000000"
                android:fontFamily="sans-serif-black"
                android:gravity="center"
                android:layout_width="60dp"
                android:layout_height="60dp"
                android:x="24"
                android:y="66"/>
          </group>
        </vector>
        EOF
        
        cat > android/app/src/main/res/drawable/ic_launcher_background.xml << 'EOF'
        <vector xmlns:android="http://schemas.android.com/apk/res/android"
            android:width="108dp"
            android:height="108dp"
            android:viewportWidth="108"
            android:viewportHeight="108">
          <path android:fillColor="#FFFFFF"
                android:pathData="M0,0h108v108h-108z"/>
        </vector>
        EOF
        
        # Update AndroidManifest.xml to use custom icon
        sed -i 's/android:icon="@mipmap\/ic_launcher"/android:icon="@drawable\/ic_launcher_foreground"/' android/app/src/main/AndroidManifest.xml
        
        # Generate PNG icons as backup
        cat > icon.svg << 'EOF'
        <svg width="512" height="512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
          <rect width="512" height="512" rx="120" ry="120" fill="white" stroke="#f0f0f0" stroke-width="8"/>
          <text x="256" y="320" font-family="Arial Black, sans-serif" font-size="240" font-weight="900" text-anchor="middle" fill="black">B</text>
        </svg>
        EOF
        
        # Create PNG icons
        for density in mdpi:48 hdpi:72 xhdpi:96 xxhdpi:144 xxxhdpi:192; do
          dir="android/app/src/main/res/mipmap-${density%:*}"
          size="${density#*:}"
          convert icon.svg -resize ${size}x${size} "$dir/ic_launcher.png"
          convert icon.svg -resize ${size}x${size} "$dir/ic_launcher_round.png"
        done
        
        # Copy and sync
        npx cap copy android
        npx cap sync android
        
        # Build APK
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: besmi-android-app
        path: besmi-mobile/android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
